site_name: 中国通用人工智能协会
repo_url: https://github.com/Hailaylin/agi-society-cn
copyright: Copyright &copy; 2016 - 2024 中国通用人工智能协会 粤ICP备2021145979号-1
theme:
  name: material
  custom_dir: overrides
  language: zh
  palette: 
        # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换为夜间模式
      primary: indigo
      accent: orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换为日间模式
      accent: cyan
  
  font: 
    text: Noto Sans SC
    code: Roboto Mono

  features:
    - header.autohide
    - navigation.tracking
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.instant

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: True

nav:
  - 关于:
    - about/about_us.md
    - about/web_arch.md
  - nars教程:
    - nars/nars_index.md
    - nars/learning_resources.md