name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: linux_amd64
    steps:
      - run: |
          echo "hello world"
      - run: |
              cd ${{ vars.WEB_WORK_DIR }}
      - run: mkdocs gh-deploy