name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: linux-amd64
    steps:
      - run: |
          ls -al
      - run: |
          cd ..
      - run: |
          ls -ld $PWD/*
      - run: |
          cd ..
      - run: |
          ls -ld $PWD/*
      - run: mkdocs gh-deploy